[workspace]
members = [
  "crates/protosearch-gen",
  "crates/protosearch-plugin",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
serde = { version = "1.0.228" }
serde_json = "1.0.149"
thiserror = "2.0.18"
