[version]
current = "0.1.0-dev"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (?P<suffix>-\w+)?
  '''

[git]
message_template = "Release {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "Cargo.toml"
